// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain;

import es.gva.dgti.gvgeoportal.domain.CapasServicioWeb;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CapasServicioWeb_Roo_Configurable {
    
    declare @type: CapasServicioWeb: @Configurable;
    
}
