// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain;

import es.gva.dgti.gvgeoportal.domain.CapasServicioWebDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.CapasServicioWebIntegrationTest;
import es.gva.dgti.gvgeoportal.service.domain.CapasServicioWebService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CapasServicioWebIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CapasServicioWebIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CapasServicioWebIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CapasServicioWebIntegrationTest: @Transactional;
    
    @Autowired
    CapasServicioWebDataOnDemand CapasServicioWebIntegrationTest.dod;
    
    @Autowired
    CapasServicioWebService CapasServicioWebIntegrationTest.capasServicioWebService;
    
    @Test
    public void CapasServicioWebIntegrationTest.testCountAllCapasServicioWebs() {
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", dod.getRandomCapasServicioWeb());
        long count = capasServicioWebService.countAllCapasServicioWebs();
        Assert.assertTrue("Counter for 'CapasServicioWeb' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testFindCapasServicioWeb() {
        CapasServicioWeb obj = dod.getRandomCapasServicioWeb();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to provide an identifier", id);
        obj = capasServicioWebService.findCapasServicioWeb(id);
        Assert.assertNotNull("Find method for 'CapasServicioWeb' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CapasServicioWeb' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testFindAllCapasServicioWebs() {
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", dod.getRandomCapasServicioWeb());
        long count = capasServicioWebService.countAllCapasServicioWebs();
        Assert.assertTrue("Too expensive to perform a find all test for 'CapasServicioWeb', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CapasServicioWeb> result = capasServicioWebService.findAllCapasServicioWebs();
        Assert.assertNotNull("Find all method for 'CapasServicioWeb' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CapasServicioWeb' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testFindCapasServicioWebEntries() {
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", dod.getRandomCapasServicioWeb());
        long count = capasServicioWebService.countAllCapasServicioWebs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CapasServicioWeb> result = capasServicioWebService.findCapasServicioWebEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CapasServicioWeb' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CapasServicioWeb' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testFlush() {
        CapasServicioWeb obj = dod.getRandomCapasServicioWeb();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to provide an identifier", id);
        obj = capasServicioWebService.findCapasServicioWeb(id);
        Assert.assertNotNull("Find method for 'CapasServicioWeb' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCapasServicioWeb(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CapasServicioWeb' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testUpdateCapasServicioWebUpdate() {
        CapasServicioWeb obj = dod.getRandomCapasServicioWeb();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to provide an identifier", id);
        obj = capasServicioWebService.findCapasServicioWeb(id);
        boolean modified =  dod.modifyCapasServicioWeb(obj);
        Integer currentVersion = obj.getVersion();
        CapasServicioWeb merged = capasServicioWebService.updateCapasServicioWeb(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CapasServicioWeb' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testSaveCapasServicioWeb() {
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", dod.getRandomCapasServicioWeb());
        CapasServicioWeb obj = dod.getNewTransientCapasServicioWeb(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CapasServicioWeb' identifier to be null", obj.getId());
        try {
            capasServicioWebService.saveCapasServicioWeb(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CapasServicioWeb' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CapasServicioWebIntegrationTest.testDeleteCapasServicioWeb() {
        CapasServicioWeb obj = dod.getRandomCapasServicioWeb();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapasServicioWeb' failed to provide an identifier", id);
        obj = capasServicioWebService.findCapasServicioWeb(id);
        capasServicioWebService.deleteCapasServicioWeb(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'CapasServicioWeb' with identifier '" + id + "'", capasServicioWebService.findCapasServicioWeb(id));
    }
    
}
