// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain;

import es.gva.dgti.gvgeoportal.domain.CapasServicioWeb;
import es.gva.dgti.gvgeoportal.domain.CapasServicioWebDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.ServicioWebDataOnDemand;
import es.gva.dgti.gvgeoportal.service.domain.CapasServicioWebService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CapasServicioWebDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CapasServicioWebDataOnDemand: @Component;
    
    private Random CapasServicioWebDataOnDemand.rnd = new SecureRandom();
    
    private List<CapasServicioWeb> CapasServicioWebDataOnDemand.data;
    
    @Autowired
    ServicioWebDataOnDemand CapasServicioWebDataOnDemand.servicioWebDataOnDemand;
    
    @Autowired
    CapasServicioWebService CapasServicioWebDataOnDemand.capasServicioWebService;
    
    public CapasServicioWeb CapasServicioWebDataOnDemand.getNewTransientCapasServicioWeb(int index) {
        CapasServicioWeb obj = new CapasServicioWeb();
        setAuditCreatedBy(obj, index);
        setAuditCreation(obj, index);
        setAuditLastUpdate(obj, index);
        setAuditLastUpdatedBy(obj, index);
        setEstiloCapa(obj, index);
        setNombreCapa(obj, index);
        setTituloCapa(obj, index);
        return obj;
    }
    
    public void CapasServicioWebDataOnDemand.setAuditCreatedBy(CapasServicioWeb obj, int index) {
        String auditCreatedBy = "auditCreatedBy_" + index;
        obj.setAuditCreatedBy(auditCreatedBy);
    }
    
    public void CapasServicioWebDataOnDemand.setAuditCreation(CapasServicioWeb obj, int index) {
        Calendar auditCreation = Calendar.getInstance();
        obj.setAuditCreation(auditCreation);
    }
    
    public void CapasServicioWebDataOnDemand.setAuditLastUpdate(CapasServicioWeb obj, int index) {
        Calendar auditLastUpdate = Calendar.getInstance();
        obj.setAuditLastUpdate(auditLastUpdate);
    }
    
    public void CapasServicioWebDataOnDemand.setAuditLastUpdatedBy(CapasServicioWeb obj, int index) {
        String auditLastUpdatedBy = "auditLastUpdatedBy_" + index;
        obj.setAuditLastUpdatedBy(auditLastUpdatedBy);
    }
    
    public void CapasServicioWebDataOnDemand.setEstiloCapa(CapasServicioWeb obj, int index) {
        String estiloCapa = "estiloCapa_" + index;
        obj.setEstiloCapa(estiloCapa);
    }
    
    public void CapasServicioWebDataOnDemand.setNombreCapa(CapasServicioWeb obj, int index) {
        String nombreCapa = "nombreCapa_" + index;
        obj.setNombreCapa(nombreCapa);
    }
    
    public void CapasServicioWebDataOnDemand.setTituloCapa(CapasServicioWeb obj, int index) {
        String tituloCapa = "tituloCapa_" + index;
        obj.setTituloCapa(tituloCapa);
    }
    
    public CapasServicioWeb CapasServicioWebDataOnDemand.getSpecificCapasServicioWeb(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CapasServicioWeb obj = data.get(index);
        Long id = obj.getId();
        return capasServicioWebService.findCapasServicioWeb(id);
    }
    
    public CapasServicioWeb CapasServicioWebDataOnDemand.getRandomCapasServicioWeb() {
        init();
        CapasServicioWeb obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return capasServicioWebService.findCapasServicioWeb(id);
    }
    
    public boolean CapasServicioWebDataOnDemand.modifyCapasServicioWeb(CapasServicioWeb obj) {
        return false;
    }
    
    public void CapasServicioWebDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = capasServicioWebService.findCapasServicioWebEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CapasServicioWeb' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CapasServicioWeb>();
        for (int i = 0; i < 10; i++) {
            CapasServicioWeb obj = getNewTransientCapasServicioWeb(i);
            try {
                capasServicioWebService.saveCapasServicioWeb(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
