// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain;

import es.gva.dgti.gvgeoportal.domain.GeoPortalDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.GeoPortalIntegrationTest;
import es.gva.dgti.gvgeoportal.service.domain.GeoPortalService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GeoPortalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GeoPortalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GeoPortalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GeoPortalIntegrationTest: @Transactional;
    
    @Autowired
    GeoPortalDataOnDemand GeoPortalIntegrationTest.dod;
    
    @Autowired
    GeoPortalService GeoPortalIntegrationTest.geoPortalService;
    
    @Test
    public void GeoPortalIntegrationTest.testCountAllGeoPortales() {
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", dod.getRandomGeoPortal());
        long count = geoPortalService.countAllGeoPortales();
        Assert.assertTrue("Counter for 'GeoPortal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GeoPortalIntegrationTest.testFindGeoPortal() {
        GeoPortal obj = dod.getRandomGeoPortal();
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to provide an identifier", id);
        obj = geoPortalService.findGeoPortal(id);
        Assert.assertNotNull("Find method for 'GeoPortal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GeoPortal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GeoPortalIntegrationTest.testFindAllGeoPortales() {
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", dod.getRandomGeoPortal());
        long count = geoPortalService.countAllGeoPortales();
        Assert.assertTrue("Too expensive to perform a find all test for 'GeoPortal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GeoPortal> result = geoPortalService.findAllGeoPortales();
        Assert.assertNotNull("Find all method for 'GeoPortal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GeoPortal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GeoPortalIntegrationTest.testFindGeoPortalEntries() {
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", dod.getRandomGeoPortal());
        long count = geoPortalService.countAllGeoPortales();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GeoPortal> result = geoPortalService.findGeoPortalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GeoPortal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GeoPortal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GeoPortalIntegrationTest.testFlush() {
        GeoPortal obj = dod.getRandomGeoPortal();
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to provide an identifier", id);
        obj = geoPortalService.findGeoPortal(id);
        Assert.assertNotNull("Find method for 'GeoPortal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGeoPortal(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GeoPortal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GeoPortalIntegrationTest.testUpdateGeoPortalUpdate() {
        GeoPortal obj = dod.getRandomGeoPortal();
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to provide an identifier", id);
        obj = geoPortalService.findGeoPortal(id);
        boolean modified =  dod.modifyGeoPortal(obj);
        Integer currentVersion = obj.getVersion();
        GeoPortal merged = geoPortalService.updateGeoPortal(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GeoPortal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GeoPortalIntegrationTest.testSaveGeoPortal() {
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to initialize correctly", dod.getRandomGeoPortal());
        GeoPortal obj = dod.getNewTransientGeoPortal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GeoPortal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GeoPortal' identifier to be null", obj.getId());
        try {
            geoPortalService.saveGeoPortal(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GeoPortal' identifier to no longer be null", obj.getId());
    }
    
}
