// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain;

import es.gva.dgti.gvgeoportal.domain.GestorCatalogo;
import es.gva.dgti.gvgeoportal.domain.GestorCatalogoDataOnDemand;
import es.gva.dgti.gvgeoportal.service.domain.GestorCatalogoService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GestorCatalogoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GestorCatalogoDataOnDemand: @Component;
    
    private Random GestorCatalogoDataOnDemand.rnd = new SecureRandom();
    
    private List<GestorCatalogo> GestorCatalogoDataOnDemand.data;
    
    @Autowired
    GestorCatalogoService GestorCatalogoDataOnDemand.gestorCatalogoService;
    
    public GestorCatalogo GestorCatalogoDataOnDemand.getNewTransientGestorCatalogo(int index) {
        GestorCatalogo obj = new GestorCatalogo();
        setAuditCreatedBy(obj, index);
        setAuditCreation(obj, index);
        setAuditLastUpdate(obj, index);
        setAuditLastUpdatedBy(obj, index);
        setNombre(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void GestorCatalogoDataOnDemand.setAuditCreatedBy(GestorCatalogo obj, int index) {
        String auditCreatedBy = "auditCreatedBy_" + index;
        obj.setAuditCreatedBy(auditCreatedBy);
    }
    
    public void GestorCatalogoDataOnDemand.setAuditCreation(GestorCatalogo obj, int index) {
        Calendar auditCreation = Calendar.getInstance();
        obj.setAuditCreation(auditCreation);
    }
    
    public void GestorCatalogoDataOnDemand.setAuditLastUpdate(GestorCatalogo obj, int index) {
        Calendar auditLastUpdate = Calendar.getInstance();
        obj.setAuditLastUpdate(auditLastUpdate);
    }
    
    public void GestorCatalogoDataOnDemand.setAuditLastUpdatedBy(GestorCatalogo obj, int index) {
        String auditLastUpdatedBy = "auditLastUpdatedBy_" + index;
        obj.setAuditLastUpdatedBy(auditLastUpdatedBy);
    }
    
    public void GestorCatalogoDataOnDemand.setNombre(GestorCatalogo obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void GestorCatalogoDataOnDemand.setUrl(GestorCatalogo obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public GestorCatalogo GestorCatalogoDataOnDemand.getSpecificGestorCatalogo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GestorCatalogo obj = data.get(index);
        Long id = obj.getId();
        return gestorCatalogoService.findGestorCatalogo(id);
    }
    
    public GestorCatalogo GestorCatalogoDataOnDemand.getRandomGestorCatalogo() {
        init();
        GestorCatalogo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return gestorCatalogoService.findGestorCatalogo(id);
    }
    
    public boolean GestorCatalogoDataOnDemand.modifyGestorCatalogo(GestorCatalogo obj) {
        return false;
    }
    
    public void GestorCatalogoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = gestorCatalogoService.findGestorCatalogoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GestorCatalogo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GestorCatalogo>();
        for (int i = 0; i < 10; i++) {
            GestorCatalogo obj = getNewTransientGestorCatalogo(i);
            try {
                gestorCatalogoService.saveGestorCatalogo(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
