// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain;

import es.gva.dgti.gvgeoportal.domain.GestorCatalogoDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.GestorCatalogoIntegrationTest;
import es.gva.dgti.gvgeoportal.service.domain.GestorCatalogoService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GestorCatalogoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GestorCatalogoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GestorCatalogoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GestorCatalogoIntegrationTest: @Transactional;
    
    @Autowired
    GestorCatalogoDataOnDemand GestorCatalogoIntegrationTest.dod;
    
    @Autowired
    GestorCatalogoService GestorCatalogoIntegrationTest.gestorCatalogoService;
    
    @Test
    public void GestorCatalogoIntegrationTest.testCountAllGestorCatalogos() {
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", dod.getRandomGestorCatalogo());
        long count = gestorCatalogoService.countAllGestorCatalogos();
        Assert.assertTrue("Counter for 'GestorCatalogo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testFindGestorCatalogo() {
        GestorCatalogo obj = dod.getRandomGestorCatalogo();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to provide an identifier", id);
        obj = gestorCatalogoService.findGestorCatalogo(id);
        Assert.assertNotNull("Find method for 'GestorCatalogo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GestorCatalogo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testFindAllGestorCatalogos() {
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", dod.getRandomGestorCatalogo());
        long count = gestorCatalogoService.countAllGestorCatalogos();
        Assert.assertTrue("Too expensive to perform a find all test for 'GestorCatalogo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GestorCatalogo> result = gestorCatalogoService.findAllGestorCatalogos();
        Assert.assertNotNull("Find all method for 'GestorCatalogo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GestorCatalogo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testFindGestorCatalogoEntries() {
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", dod.getRandomGestorCatalogo());
        long count = gestorCatalogoService.countAllGestorCatalogos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GestorCatalogo> result = gestorCatalogoService.findGestorCatalogoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GestorCatalogo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GestorCatalogo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testFlush() {
        GestorCatalogo obj = dod.getRandomGestorCatalogo();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to provide an identifier", id);
        obj = gestorCatalogoService.findGestorCatalogo(id);
        Assert.assertNotNull("Find method for 'GestorCatalogo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGestorCatalogo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GestorCatalogo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testUpdateGestorCatalogoUpdate() {
        GestorCatalogo obj = dod.getRandomGestorCatalogo();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to provide an identifier", id);
        obj = gestorCatalogoService.findGestorCatalogo(id);
        boolean modified =  dod.modifyGestorCatalogo(obj);
        Integer currentVersion = obj.getVersion();
        GestorCatalogo merged = gestorCatalogoService.updateGestorCatalogo(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GestorCatalogo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testSaveGestorCatalogo() {
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", dod.getRandomGestorCatalogo());
        GestorCatalogo obj = dod.getNewTransientGestorCatalogo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GestorCatalogo' identifier to be null", obj.getId());
        try {
            gestorCatalogoService.saveGestorCatalogo(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GestorCatalogo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GestorCatalogoIntegrationTest.testDeleteGestorCatalogo() {
        GestorCatalogo obj = dod.getRandomGestorCatalogo();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GestorCatalogo' failed to provide an identifier", id);
        obj = gestorCatalogoService.findGestorCatalogo(id);
        gestorCatalogoService.deleteGestorCatalogo(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'GestorCatalogo' with identifier '" + id + "'", gestorCatalogoService.findGestorCatalogo(id));
    }
    
}
