// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain.components;

import es.gva.dgti.gvgeoportal.domain.components.ConfCapasTematicasDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ConfCapasTematicasDataOnDemand_Roo_Configurable {
    
    declare @type: ConfCapasTematicasDataOnDemand: @Configurable;
    
}
