// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain.components;

import es.gva.dgti.gvgeoportal.domain.components.ConfAyudaBuscadorDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.components.ConfAyudaBuscadorIntegrationTest;
import es.gva.dgti.gvgeoportal.service.domain.ConfAyudaBuscadorService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConfAyudaBuscadorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConfAyudaBuscadorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConfAyudaBuscadorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConfAyudaBuscadorIntegrationTest: @Transactional;
    
    @Autowired
    ConfAyudaBuscadorDataOnDemand ConfAyudaBuscadorIntegrationTest.dod;
    
    @Autowired
    ConfAyudaBuscadorService ConfAyudaBuscadorIntegrationTest.confAyudaBuscadorService;
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testCountAllConfAyudaBuscadors() {
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", dod.getRandomConfAyudaBuscador());
        long count = confAyudaBuscadorService.countAllConfAyudaBuscadors();
        Assert.assertTrue("Counter for 'ConfAyudaBuscador' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testFindConfAyudaBuscador() {
        ConfAyudaBuscador obj = dod.getRandomConfAyudaBuscador();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to provide an identifier", id);
        obj = confAyudaBuscadorService.findConfAyudaBuscador(id);
        Assert.assertNotNull("Find method for 'ConfAyudaBuscador' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConfAyudaBuscador' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testFindAllConfAyudaBuscadors() {
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", dod.getRandomConfAyudaBuscador());
        long count = confAyudaBuscadorService.countAllConfAyudaBuscadors();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConfAyudaBuscador', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConfAyudaBuscador> result = confAyudaBuscadorService.findAllConfAyudaBuscadors();
        Assert.assertNotNull("Find all method for 'ConfAyudaBuscador' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConfAyudaBuscador' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testFindConfAyudaBuscadorEntries() {
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", dod.getRandomConfAyudaBuscador());
        long count = confAyudaBuscadorService.countAllConfAyudaBuscadors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConfAyudaBuscador> result = confAyudaBuscadorService.findConfAyudaBuscadorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ConfAyudaBuscador' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConfAyudaBuscador' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testFlush() {
        ConfAyudaBuscador obj = dod.getRandomConfAyudaBuscador();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to provide an identifier", id);
        obj = confAyudaBuscadorService.findConfAyudaBuscador(id);
        Assert.assertNotNull("Find method for 'ConfAyudaBuscador' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConfAyudaBuscador(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ConfAyudaBuscador' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testUpdateConfAyudaBuscadorUpdate() {
        ConfAyudaBuscador obj = dod.getRandomConfAyudaBuscador();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to provide an identifier", id);
        obj = confAyudaBuscadorService.findConfAyudaBuscador(id);
        boolean modified =  dod.modifyConfAyudaBuscador(obj);
        Integer currentVersion = obj.getVersion();
        ConfAyudaBuscador merged = (ConfAyudaBuscador)confAyudaBuscadorService.updateConfAyudaBuscador(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ConfAyudaBuscador' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testSaveConfAyudaBuscador() {
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", dod.getRandomConfAyudaBuscador());
        ConfAyudaBuscador obj = dod.getNewTransientConfAyudaBuscador(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConfAyudaBuscador' identifier to be null", obj.getId());
        try {
            confAyudaBuscadorService.saveConfAyudaBuscador(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ConfAyudaBuscador' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConfAyudaBuscadorIntegrationTest.testDeleteConfAyudaBuscador() {
        ConfAyudaBuscador obj = dod.getRandomConfAyudaBuscador();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfAyudaBuscador' failed to provide an identifier", id);
        obj = confAyudaBuscadorService.findConfAyudaBuscador(id);
        confAyudaBuscadorService.deleteConfAyudaBuscador(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'ConfAyudaBuscador' with identifier '" + id + "'", confAyudaBuscadorService.findConfAyudaBuscador(id));
    }
    
}
