// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain.components;

import es.gva.dgti.gvgeoportal.domain.GeoPortalDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.ServicioWebDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.components.ConfMiniMapa;
import es.gva.dgti.gvgeoportal.domain.components.ConfMiniMapaDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.enumerated.TipoComponente;
import es.gva.dgti.gvgeoportal.service.domain.ConfMiniMapaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ConfMiniMapaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConfMiniMapaDataOnDemand: @Component;
    
    private Random ConfMiniMapaDataOnDemand.rnd = new SecureRandom();
    
    private List<ConfMiniMapa> ConfMiniMapaDataOnDemand.data;
    
    @Autowired
    GeoPortalDataOnDemand ConfMiniMapaDataOnDemand.geoPortalDataOnDemand;
    
    @Autowired
    ServicioWebDataOnDemand ConfMiniMapaDataOnDemand.servicioWebDataOnDemand;
    
    @Autowired
    ConfMiniMapaService ConfMiniMapaDataOnDemand.confMiniMapaService;
    
    public ConfMiniMapa ConfMiniMapaDataOnDemand.getNewTransientConfMiniMapa(int index) {
        ConfMiniMapa obj = new ConfMiniMapa();
        setAuditCreatedBy(obj, index);
        setAuditCreation(obj, index);
        setAuditLastUpdate(obj, index);
        setAuditLastUpdatedBy(obj, index);
        setTipo(obj, index);
        return obj;
    }
    
    public void ConfMiniMapaDataOnDemand.setAuditCreatedBy(ConfMiniMapa obj, int index) {
        String auditCreatedBy = "auditCreatedBy_" + index;
        obj.setAuditCreatedBy(auditCreatedBy);
    }
    
    public void ConfMiniMapaDataOnDemand.setAuditCreation(ConfMiniMapa obj, int index) {
        Calendar auditCreation = Calendar.getInstance();
        obj.setAuditCreation(auditCreation);
    }
    
    public void ConfMiniMapaDataOnDemand.setAuditLastUpdate(ConfMiniMapa obj, int index) {
        Calendar auditLastUpdate = Calendar.getInstance();
        obj.setAuditLastUpdate(auditLastUpdate);
    }
    
    public void ConfMiniMapaDataOnDemand.setAuditLastUpdatedBy(ConfMiniMapa obj, int index) {
        String auditLastUpdatedBy = "auditLastUpdatedBy_" + index;
        obj.setAuditLastUpdatedBy(auditLastUpdatedBy);
    }
    
    public void ConfMiniMapaDataOnDemand.setTipo(ConfMiniMapa obj, int index) {
        TipoComponente tipo = TipoComponente.class.getEnumConstants()[0];
        obj.setTipo(tipo);
    }
    
    public ConfMiniMapa ConfMiniMapaDataOnDemand.getSpecificConfMiniMapa(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ConfMiniMapa obj = data.get(index);
        Long id = obj.getId();
        return confMiniMapaService.findConfMiniMapa(id);
    }
    
    public ConfMiniMapa ConfMiniMapaDataOnDemand.getRandomConfMiniMapa() {
        init();
        ConfMiniMapa obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return confMiniMapaService.findConfMiniMapa(id);
    }
    
    public boolean ConfMiniMapaDataOnDemand.modifyConfMiniMapa(ConfMiniMapa obj) {
        return false;
    }
    
    public void ConfMiniMapaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = confMiniMapaService.findConfMiniMapaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ConfMiniMapa' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ConfMiniMapa>();
        for (int i = 0; i < 10; i++) {
            ConfMiniMapa obj = getNewTransientConfMiniMapa(i);
            try {
                confMiniMapaService.saveConfMiniMapa(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
