// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain.components;

import es.gva.dgti.gvgeoportal.domain.components.ConfMiniMapaDataOnDemand;
import es.gva.dgti.gvgeoportal.domain.components.ConfMiniMapaIntegrationTest;
import es.gva.dgti.gvgeoportal.service.domain.ConfMiniMapaService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConfMiniMapaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConfMiniMapaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConfMiniMapaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConfMiniMapaIntegrationTest: @Transactional;
    
    @Autowired
    ConfMiniMapaDataOnDemand ConfMiniMapaIntegrationTest.dod;
    
    @Autowired
    ConfMiniMapaService ConfMiniMapaIntegrationTest.confMiniMapaService;
    
    @Test
    public void ConfMiniMapaIntegrationTest.testCountAllConfMiniMapas() {
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", dod.getRandomConfMiniMapa());
        long count = confMiniMapaService.countAllConfMiniMapas();
        Assert.assertTrue("Counter for 'ConfMiniMapa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testFindConfMiniMapa() {
        ConfMiniMapa obj = dod.getRandomConfMiniMapa();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to provide an identifier", id);
        obj = confMiniMapaService.findConfMiniMapa(id);
        Assert.assertNotNull("Find method for 'ConfMiniMapa' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConfMiniMapa' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testFindAllConfMiniMapas() {
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", dod.getRandomConfMiniMapa());
        long count = confMiniMapaService.countAllConfMiniMapas();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConfMiniMapa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConfMiniMapa> result = confMiniMapaService.findAllConfMiniMapas();
        Assert.assertNotNull("Find all method for 'ConfMiniMapa' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConfMiniMapa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testFindConfMiniMapaEntries() {
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", dod.getRandomConfMiniMapa());
        long count = confMiniMapaService.countAllConfMiniMapas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConfMiniMapa> result = confMiniMapaService.findConfMiniMapaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ConfMiniMapa' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConfMiniMapa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testFlush() {
        ConfMiniMapa obj = dod.getRandomConfMiniMapa();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to provide an identifier", id);
        obj = confMiniMapaService.findConfMiniMapa(id);
        Assert.assertNotNull("Find method for 'ConfMiniMapa' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConfMiniMapa(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ConfMiniMapa' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testUpdateConfMiniMapaUpdate() {
        ConfMiniMapa obj = dod.getRandomConfMiniMapa();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to provide an identifier", id);
        obj = confMiniMapaService.findConfMiniMapa(id);
        boolean modified =  dod.modifyConfMiniMapa(obj);
        Integer currentVersion = obj.getVersion();
        ConfMiniMapa merged = (ConfMiniMapa)confMiniMapaService.updateConfMiniMapa(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ConfMiniMapa' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testSaveConfMiniMapa() {
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", dod.getRandomConfMiniMapa());
        ConfMiniMapa obj = dod.getNewTransientConfMiniMapa(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConfMiniMapa' identifier to be null", obj.getId());
        try {
            confMiniMapaService.saveConfMiniMapa(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ConfMiniMapa' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConfMiniMapaIntegrationTest.testDeleteConfMiniMapa() {
        ConfMiniMapa obj = dod.getRandomConfMiniMapa();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfMiniMapa' failed to provide an identifier", id);
        obj = confMiniMapaService.findConfMiniMapa(id);
        confMiniMapaService.deleteConfMiniMapa(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'ConfMiniMapa' with identifier '" + id + "'", confMiniMapaService.findConfMiniMapa(id));
    }
    
}
