// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.gva.dgti.gvgeoportal.domain.components;

import es.gva.dgti.gvgeoportal.domain.components.ConfVistasPredefinidas;
import javax.persistence.Entity;

privileged aspect ConfVistasPredefinidas_Roo_Jpa_Entity {
    
    declare @type: ConfVistasPredefinidas: @Entity;
    
}
